name: AndroidBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v3

      - name: JDK 17のセットアップ
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradleの実行権限付与
        run: chmod +x ./gradlew

      - name: デバッグビルドの実行
        run: ./gradlew assembleDebug

      - name: ビルド成果物のアップロード
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

